/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.DBConnection;
import Database.QueryFunction;
import Database.RegExpCheck;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author mangesh
 */
public class AdminLogin extends javax.swing.JFrame {

    DBConnection conObj = new DBConnection();
    Connection con;
    java.sql.PreparedStatement ps;
    ResultSet rs;
    public static String Uname = null;
    public static String URoleName = null;
    public static double serverSize;

    /**
     * Creates new form Login_page
     */
    public AdminLogin() {
        initComponents();
//        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlMain = new javax.swing.JPanel();
        lblUname = new javax.swing.JLabel();
        lblPasswd = new javax.swing.JLabel();
        txtAuname = new javax.swing.JTextField();
        Login_btn = new javax.swing.JButton();
        Clr_btn = new javax.swing.JButton();
        txtApasswd = new javax.swing.JPasswordField();
        PnlTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlMain.setBackground(new java.awt.Color(34, 49, 63));
        PnlMain.setLayout(new java.awt.GridBagLayout());

        lblUname.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblUname.setForeground(new java.awt.Color(255, 255, 255));
        lblUname.setText(" UserName:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 98, 0, 0);
        PnlMain.add(lblUname, gridBagConstraints);

        lblPasswd.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblPasswd.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswd.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 98, 0, 0);
        PnlMain.add(lblPasswd, gridBagConstraints);

        txtAuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAunameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 223;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 98, 0, 71);
        PnlMain.add(txtAuname, gridBagConstraints);

        Login_btn.setBackground(new java.awt.Color(0, 177, 106));
        Login_btn.setText("Login");
        Login_btn.setToolTipText("");
        Login_btn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Login_btnMouseMoved(evt);
            }
        });
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 98, 68, 0);
        PnlMain.add(Login_btn, gridBagConstraints);

        Clr_btn.setBackground(new java.awt.Color(242, 38, 19));
        Clr_btn.setText("Clear");
        Clr_btn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Clr_btnMouseMoved(evt);
            }
        });
        Clr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clr_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 46, 68, 0);
        PnlMain.add(Clr_btn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 223;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 98, 0, 71);
        PnlMain.add(txtApasswd, gridBagConstraints);

        getContentPane().add(PnlMain, java.awt.BorderLayout.CENTER);

        PnlTitle.setBackground(new java.awt.Color(228, 241, 254));

        jLabel1.setBackground(new java.awt.Color(248, 235, 239));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 36, 89));
        jLabel1.setText("ADMIN LOGIN ");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_home-icon.png"))); // NOI18N
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PnlTitleLayout = new javax.swing.GroupLayout(PnlTitle);
        PnlTitle.setLayout(PnlTitleLayout);
        PnlTitleLayout.setHorizontalGroup(
            PnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        PnlTitleLayout.setVerticalGroup(
            PnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PnlTitle, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAunameActionPerformed
        // TODO add your handling code here:
        txtAuname.getText();
        txtAuname.getText();

    }//GEN-LAST:event_txtAunameActionPerformed

    private void Clr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clr_btnActionPerformed
        // TODO add your handling code here:
        txtAuname.setText("");
        txtApasswd.setText("");
    }//GEN-LAST:event_Clr_btnActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        
        try {
            QueryFunction qf = new QueryFunction();
            con = conObj.dbConnection();
            String email = txtAuname.getText().trim();            
            System.out.println("email" + "  " + email);
            String pass = new String(txtApasswd.getPassword());
            System.out.println("pass" + "  " + pass);
            
            if (email.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter User Name", "Error", JOptionPane.ERROR_MESSAGE);
                txtAuname.requestFocus();//for getting focus
            } else if (pass.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter Password", "Error", JOptionPane.ERROR_MESSAGE);
                txtApasswd.requestFocus();
            } else {
                //matching with regular expn pattern
                RegExpCheck regexpn = new RegExpCheck();
                if (!regexpn.matchUserName(email)) {
                    JOptionPane.showMessageDialog(this, "Enter Enter Valid Username !!!");
                    txtAuname.requestFocus();
                } else if (!regexpn.matchPassword(pass)) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Password !!!");
                    txtApasswd.requestFocus();
                } else {
                    System.out.println("i m here");
                    String UserName = "";
                    String Password = "";
                    java.sql.PreparedStatement ps2 = con.prepareStatement("select Email,password from adminlogin where Email=? and password=?");
                    ps2.setString(1, email);
                    ps2.setString(2, pass);
                    
                    ResultSet rs = ps2.executeQuery();
                    while (rs.next()) {
                        UserName = rs.getString(1);
                        Password = rs.getString(2);
                        if (UserName.equals(email) && Password.equals(pass)) {
                            Uname = UserName;
                            System.out.println("UserName=>" + Uname);
                            JOptionPane.showMessageDialog(this, "Login Successfull !!!", "Success", JOptionPane.INFORMATION_MESSAGE);
                            System.out.println("User Login");
                            
                            this.dispose();
                            UserDetailsFrame f = new UserDetailsFrame();
                            f.setVisible(true);                            
                            
                        } else {
                            JOptionPane.showMessageDialog(this, " please enter valid Login Details..!");
                        }
                    }

                    /*     if (f == 1) {
                        System.out.println("Logged UserName=" + UserName + "\t Password=" + Password);
                        String RoleName = qf.getRoleName(UserName, Password);
                        URoleName = RoleName;
                        System.out.println("Role=" + RoleName);

                        //checking role of the user
                        if (RoleName.equals("Admin")) {
                            //Admin Login
                            JOptionPane.showMessageDialog(this, "Login Successfull !!!", "Success", JOptionPane.INFORMATION_MESSAGE);
                            //adding new panel for Admin
                            pnlNew.removeAll();
                            pnlNew.add(new pnlSubHome());
                            pnlSubHome.lbName.setText(UserName);
                            pnlSubHome.lbRevocation.setVisible(true);
                            pnlSubHome.lbGraph.setVisible(true);
                            pnlSubHome.lbDecryption.setVisible(false);
                            //pnlSubHome.lbExtra.setVisible(true);
                            pnlSubHome.lbUpload.setVisible(true);
                            pnlNew.updateUI();
                        } else {
                            //the panel for normal user     
                            JOptionPane.showMessageDialog(this, "Login Successfull !!!", "Success", JOptionPane.INFORMATION_MESSAGE);
                            System.out.println("User Login");
                            pnlNew.removeAll();
                            pnlNew.add(new pnlSubHome());
                            pnlSubHome.lbName.setText(UserName);
                            pnlSubHome.lbRevocation.setVisible(false);
                            pnlSubHome.lbGraph.setVisible(false);
                            pnlSubHome.lbDecryption.setVisible(true);
                            //pnlSubHome.lbExtra.setVisible(false);
                            pnlSubHome.lbUpload.setVisible(false);
                            pnlNew.updateUI();
                            RecieveResponseFromTPA r=new RecieveResponseFromTPA();
                            r.start();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Incorrect Email ID And Password");
                    } */
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        

    }//GEN-LAST:event_Login_btnActionPerformed

    private void Login_btnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_btnMouseMoved
        // TODO add your handling code here:
        Login_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Login_btnMouseMoved

    private void Clr_btnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clr_btnMouseMoved
        // TODO add your handling code here:
        Clr_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Clr_btnMouseMoved

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        // TODO add your handling code here:
        jLabel2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel2MouseMoved

    /**
     * @param args the command line arguments
     */
// public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login_page().setVisible(true);
//                new Login_page().setLocationRelativeTo(null);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clr_btn;
    private javax.swing.JButton Login_btn;
    private javax.swing.JPanel PnlMain;
    private javax.swing.JPanel PnlTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPasswd;
    private javax.swing.JLabel lblUname;
    private javax.swing.JPasswordField txtApasswd;
    private javax.swing.JTextField txtAuname;
    // End of variables declaration//GEN-END:variables
}
