/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Database.DBConnection;
import Database.QueryFunction;
import Database.RegExpCheck;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import GUI.UserDashBord;
import GUI.Register;
import java.text.ParseException;


/**
 *
 * @author mangesh
 */
public class UserLogin extends javax.swing.JFrame {
    DBConnection conObj = new DBConnection();
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    public static String email;
    public static String pass;
    public static String Uname = null;
    public static String cloudId = null;
    public static double serverSize;

    /**
     * Creates new form Login_page
     */
    public UserLogin() {
        initComponents();
//        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlMain = new javax.swing.JPanel();
        lblUname = new javax.swing.JLabel();
        lblPasswd = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        Login_btn = new javax.swing.JButton();
        Clr_btn = new javax.swing.JButton();
        lblRegister = new javax.swing.JLabel();
        txtpasswd = new javax.swing.JPasswordField();
        PnlTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbluserloginhome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlMain.setBackground(new java.awt.Color(34, 49, 63));
        PnlMain.setLayout(new java.awt.GridBagLayout());

        lblUname.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblUname.setForeground(new java.awt.Color(255, 255, 255));
        lblUname.setText("User Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 98, 0, 0);
        PnlMain.add(lblUname, gridBagConstraints);

        lblPasswd.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblPasswd.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswd.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 98, 0, 0);
        PnlMain.add(lblPasswd, gridBagConstraints);

        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 223;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 98, 0, 71);
        PnlMain.add(txtuname, gridBagConstraints);

        Login_btn.setBackground(new java.awt.Color(0, 177, 106));
        Login_btn.setText("Login");
        Login_btn.setToolTipText("");
        Login_btn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Login_btnMouseMoved(evt);
            }
        });
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 98, 0, 0);
        PnlMain.add(Login_btn, gridBagConstraints);

        Clr_btn.setBackground(new java.awt.Color(242, 38, 19));
        Clr_btn.setText("Clear");
        Clr_btn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Clr_btnMouseMoved(evt);
            }
        });
        Clr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clr_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 46, 0, 0);
        PnlMain.add(Clr_btn, gridBagConstraints);

        lblRegister.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setText("Not Registered? Click Here");
        lblRegister.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblRegisterMouseMoved(evt);
            }
        });
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 98, 28, 0);
        PnlMain.add(lblRegister, gridBagConstraints);

        txtpasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 223;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 98, 0, 71);
        PnlMain.add(txtpasswd, gridBagConstraints);

        getContentPane().add(PnlMain, java.awt.BorderLayout.CENTER);

        PnlTitle.setBackground(new java.awt.Color(228, 241, 254));

        jLabel1.setBackground(new java.awt.Color(248, 235, 239));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 36, 89));
        jLabel1.setText("USER LOGIN ");

        jlbluserloginhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_home-icon.png"))); // NOI18N
        jlbluserloginhome.setText("jLabel2");
        jlbluserloginhome.setMaximumSize(new java.awt.Dimension(40, 40));
        jlbluserloginhome.setMinimumSize(new java.awt.Dimension(40, 40));
        jlbluserloginhome.setPreferredSize(new java.awt.Dimension(40, 40));
        jlbluserloginhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbluserloginhomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PnlTitleLayout = new javax.swing.GroupLayout(PnlTitle);
        PnlTitle.setLayout(PnlTitleLayout);
        PnlTitleLayout.setHorizontalGroup(
            PnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbluserloginhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(122, 122, 122))
        );
        PnlTitleLayout.setVerticalGroup(
            PnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbluserloginhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PnlTitle, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
        txtuname.getText();
        txtuname.getText();

    }//GEN-LAST:event_txtunameActionPerformed

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
        this.dispose();
        try {
            Register1 r=new Register1();
            r.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
     

    }//GEN-LAST:event_lblRegisterMouseClicked

    private void Clr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clr_btnActionPerformed
        // TODO add your handling code here:
        txtuname.setText("");
        txtpasswd.setText("");
    }//GEN-LAST:event_Clr_btnActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
      
        try {
            QueryFunction qf = new QueryFunction();
            con = conObj.dbConnection();
             email = txtuname.getText().trim(); 
             pass = new String(txtpasswd.getPassword());
           
            if (email.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter User Name", "Error", JOptionPane.ERROR_MESSAGE);
                txtuname.requestFocus();//for getting focus
            } else if (pass.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter Password", "Error", JOptionPane.ERROR_MESSAGE);
                txtpasswd.requestFocus();
            } else {
                //matching with regular expn pattern
                RegExpCheck regexpn = new RegExpCheck();
                if (!regexpn.matchUserName(email)) {
                    JOptionPane.showMessageDialog(this, "Enter Enter Valid Username !!!");
                    txtuname.requestFocus();
                } else if (!regexpn.matchPassword(pass)) {
                    JOptionPane.showMessageDialog(this, "Please Enter Valid Password !!!");
                    txtpasswd.requestFocus();
                } else {
                    String UserName = "";
                    String Password = "";
                    PreparedStatement ps = con.prepareStatement("select Email,password from registration where Email=? and password=?");
                    ps.setString(1,email);
                    ps.setString(2,pass);
                    
                    ResultSet rs = ps.executeQuery();
                    while (rs.next()) {
                        UserName = rs.getString(1);
                        Password = rs.getString(2);
                       
                    }
                     if (UserName.equals(email) && Password.equals(pass)) {
                            Uname = UserName;
                            System.out.println("UserName=>"+Uname);
                             JOptionPane.showMessageDialog(this, "Login Successfull !!!", "Success", JOptionPane.INFORMATION_MESSAGE);
                             System.out.println("User Login");
                             this.dispose();
                             new UserDashBord().setVisible(true);
                           
                        }else{
                         JOptionPane.showMessageDialog(this, "Enter Valid EmailId and Password..");
                     }
               

                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println("tttt");
     

    }//GEN-LAST:event_Login_btnActionPerformed

    private void lblRegisterMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseMoved
        // TODO add your handling code here:
        lblRegister.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblRegisterMouseMoved

    private void Login_btnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_btnMouseMoved
        // TODO add your handling code here:
         Login_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Login_btnMouseMoved

    private void Clr_btnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clr_btnMouseMoved
        // TODO add your handling code here:
         Clr_btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Clr_btnMouseMoved

    private void txtpasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswdActionPerformed

    private void jlbluserloginhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbluserloginhomeMouseClicked
        // TODO add your handling code here:
         this.dispose();
         new MainFrame().setVisible(true);
        
    }//GEN-LAST:event_jlbluserloginhomeMouseClicked

    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
                new UserLogin().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clr_btn;
    private javax.swing.JButton Login_btn;
    private javax.swing.JPanel PnlMain;
    private javax.swing.JPanel PnlTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbluserloginhome;
    private javax.swing.JLabel lblPasswd;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblUname;
    private javax.swing.JPasswordField txtpasswd;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
